name: Security Scan Orchestration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  trigger-security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        
    - name: Trigger Security Scan Workflow
      run: |
        # Create GitHub payload for Step Functions
        PAYLOAD=$(cat <<EOF
        {
          "repository": {
            "id": ${{ github.event.repository.id }},
            "name": "${{ github.event.repository.name }}",
            "full_name": "${{ github.event.repository.full_name }}",
            "owner": {
              "login": "${{ github.event.repository.owner.login }}",
              "id": ${{ github.event.repository.owner.id }}
            },
            "html_url": "${{ github.event.repository.html_url }}",
            "clone_url": "${{ github.event.repository.clone_url }}",
            "language": "${{ github.event.repository.language }}",
            "default_branch": "${{ github.event.repository.default_branch }}"
          },
          "head_commit": {
            "id": "${{ github.sha }}",
            "message": $(echo '${{ github.event.head_commit.message }}' | jq -R .),
            "timestamp": "${{ github.event.head_commit.timestamp }}",
            "author": {
              "name": "${{ github.event.head_commit.author.name }}",
              "email": "${{ github.event.head_commit.author.email }}"
            },
            "added": $(echo '${{ toJson(github.event.head_commit.added) }}'),
            "modified": $(echo '${{ toJson(github.event.head_commit.modified) }}'),
            "removed": $(echo '${{ toJson(github.event.head_commit.removed) }}')
          },
          "ref": "${{ github.ref }}",
          "before": "${{ github.event.before }}",
          "after": "${{ github.event.after }}",
          "pusher": {
            "name": "${{ github.event.pusher.name }}",
            "email": "${{ github.event.pusher.email }}"
          },
          "sender": {
            "login": "${{ github.event.sender.login }}",
            "id": ${{ github.event.sender.id }}
          }
        }
        EOF
        )
        
        # Execute Step Functions state machine
        EXECUTION_NAME="github-${{ github.run_id }}-${{ github.run_attempt }}"
        
        aws stepfunctions start-execution \
          --state-machine-arn "arn:aws:states:us-west-2:047786098634:stateMachine:security-scan-orchestration-dev" \
          --name "$EXECUTION_NAME" \
          --input "$PAYLOAD"
        
        echo "🚀 Security scan triggered successfully!"
        echo "Execution name: $EXECUTION_NAME"
        echo "Monitor progress: https://us-west-2.console.aws.amazon.com/states/home?region=us-west-2"
